Definim algunes constants:

In [395]:

import os
import numpy as np
import copy

class SnowmanConstants:
    """CONSTANTS FOR CELL IDENTIFICATION"""
    WALL_CELL = 0
    OUT_OFF_GRID_CELL = 0
    SMALL_BALL_CELL = 1
    MEDIUM_BALL_CELL = 2
    SMALL_BALL_ON_MEDIUM_BALL_CELL= 3
    LARGE_BALL_CELL = 4
    SMALL_BALL_ON_LARGE_BALL_CELL = 5
    MEDIUM_BALL_ON_LARGE_BALL_CELL = 6
    FULL_SNOW_MAN_CELL= 7
    GRASS_CELL = 8
    SNOW_CELL = 9
    CHARACTER_ON_SNOW_CELL = 10
    CHARACTER_ON_GRASS_CELL = 11

    """CONSTANTS FOR TOKEN IDENTIFICATION"""
    WALL_TOKEN = '#'
    OUT_OFF_GRID_TOKEN = 'x'
    SMALL_BALL_TOKEN = '1'
    MEDIUM_BALL_TOKEN = '2'
    SMALL_BALL_ON_MEDIUM_BALL_TOKEN = '3'
    LARGE_BALL_TOKEN = '4'
    SMALL_BALL_ON_LARGE_BALL_TOKEN = '5'
    MEDIUM_BALL_ON_LARGE_BALL_TOKEN = '6'
    FULL_SNOW_MAN_TOKEN= '7'
    GRASS_TOKEN = ','
    SNOW_TOKEN = '.'
    CHARACTER_ON_SNOW_TOKEN = 'p'
    CHARACTER_ON_GRASS_TOKEN = 'q'
    CHARACTER_LEAVE_CELL = 'pq'

    """DEFINE REWARDS"""
    error=-100
    tonto=-50
    cami=1
    cim=50
    convertir=10
    bingo=200

    actions=[
        [[None,None,None,error],[None,None,None,error],[None,None,None,error],[None,None,None,error],[None,None,None,error],[None,None,None,error],[None,None,None,error],[None,None,None,error],[None,None,None,error],[None,None,None,error]],
        [[None,None,None,error],[None,None,None,tonto],['pq',11,3,cim],[None,None,None,tonto],['pq',11,5,cim],[None,None,None,tonto],['pq',11,7,bingo],[None,None,None,tonto],['pq',11,1,cami],['pq',11,2,convertir]],
        [[None,None,None,error],[None,None,None,tonto],[None,None,None,tonto],[None,None,None,tonto],['pq',11,6,cim],[None,None,None,tonto],[None,None,None,tonto],[None,None,None,tonto],['pq',11,2,cami],['pq',11,4,convertir]],
        [[None,None,None,error],[None,None,None,tonto],[None,None,None,tonto],[None,None,None,tonto],[None,None,None,tonto],[None,None,None,tonto],[None,None,None,tonto],[None,None,None,tonto],[None,2,1,-cim],[None,2,2,-cim]],
        [[None,None,None,error],[None,None,None,tonto],[None,None,None,tonto],[None,None,None,tonto],[None,None,None,tonto],[None,None,None,tonto],[None,None,None,tonto],[None,None,None,tonto],['pq',11,4,cami],['pq',11,4,cami]],
        [[None,None,None,error],[None,None,None,tonto],[None,None,None,tonto],[None,None,None,tonto],[None,None,None,tonto],[None,None,None,tonto],[None,None,None,tonto],[None,None,None,tonto],[None,4,1,-cim],[None,4,2,-cim]],
        [[None,None,None,error],[None,None,None,tonto],[None,None,None,tonto],[None,None,None,tonto],[None,None,None,tonto],[None,None,None,tonto],[None,None,None,tonto],[None,None,None,tonto],[None,4,2,-cim],[None,4,4,-cim]],   
        [[None,None,None,error],[None,None,None,error],[None,None,None,error],[None,None,None,error],[None,None,None,error],[None,None,None,error],[None,None,None,error],[None,None,None,error],[None,None,None,error],[None,None,None,error]],
        [['pq',11,None,cami],['pq',11,None,cami],['pq',11,None,cami],['pq',11,None,cami],['pq',11,None,cami],['pq',11,None,cami],['pq',11,None,cami],['pq',11,None,tonto],['pq',11,None,cami],['pq',11,None,cami]],
        [['pq',10,None,cami],['pq',10,None,cami],['pq',10,None,cami],['pq',10,None,cami],['pq',10,None,cami],['pq',10,None,cami],['pq',10,None,cami],['pq',10,None,tonto],['pq',10,None,cami],['pq',10,None,cami]]
    ]

    @staticmethod
    def get_cell_codes_array():
        return [
            SnowmanConstants.WALL_CELL,
            SnowmanConstants.OUT_OFF_GRID_CELL,
            SnowmanConstants.SMALL_BALL_CELL,
            SnowmanConstants.MEDIUM_BALL_CELL,
            SnowmanConstants.SMALL_BALL_ON_MEDIUM_BALL_CELL,
            SnowmanConstants.LARGE_BALL_CELL,
            SnowmanConstants.SMALL_BALL_ON_LARGE_BALL_CELL,
            SnowmanConstants.MEDIUM_BALL_ON_LARGE_BALL_CELL,
            SnowmanConstants.FULL_SNOW_MAN_CELL,
            SnowmanConstants.GRASS_CELL,
            SnowmanConstants.SNOW_CELL,
            SnowmanConstants.CHARACTER_ON_SNOW_CELL,
            SnowmanConstants.CHARACTER_ON_GRASS_CELL
        ]
    
    @staticmethod
    def get_tokens_array():
        return [
            SnowmanConstants.WALL_TOKEN,
            SnowmanConstants.OUT_OFF_GRID_TOKEN,
            SnowmanConstants.SMALL_BALL_TOKEN,
            SnowmanConstants.MEDIUM_BALL_TOKEN,
            SnowmanConstants.SMALL_BALL_ON_MEDIUM_BALL_TOKEN,
            SnowmanConstants.LARGE_BALL_TOKEN,
            SnowmanConstants.SMALL_BALL_ON_LARGE_BALL_TOKEN,
            SnowmanConstants.MEDIUM_BALL_ON_LARGE_BALL_TOKEN,
            SnowmanConstants.FULL_SNOW_MAN_TOKEN,
            SnowmanConstants.GRASS_TOKEN,
            SnowmanConstants.SNOW_TOKEN,
            SnowmanConstants.CHARACTER_ON_SNOW_TOKEN,
            SnowmanConstants.CHARACTER_ON_GRASS_TOKEN
        ]




        

Definim l'environment:

In [396]:
import gym
from gym import spaces

class SnowmanEnvironment(gym.Env):

    ENCODED_TEXT_MODE = 0
    DECODED_TEXT_MODE = 1
    GRAPHIC_MODE = 2 #futur, encara no implementat

    def __init__(self, map_file, n, m):
        super(SnowmanEnvironment, self).__init__()
        self.n = n
        self.m = m
        self.map, self.decoded_map = self._read_and_encode_map(map_file, n, m)
        self.original_map = copy.deepcopy(self.map) #Conserve the original map to allow reset
        
        
        #Search the agent position
        for i in range(n):
            for (j) in range(m):
                if (self.map[i,j] == SnowmanConstants.CHARACTER_ON_SNOW_CELL or 
                    self.map[i,j] == SnowmanConstants.CHARACTER_ON_GRASS_CELL):
                    self.agent_position = (i, j)
                    break
        self.original_agent_position = copy.deepcopy(self.agent_position)

        #Atributs necessaris per gym:
        self.action_space = spaces.Discrete(4)
        
        self.observation_space = spaces.Box(low=0, high=255, shape=(n, m), dtype=np.float64)


    def reset(self):
        self.map = copy.deepcopy(self.original_map)
        self.agent_position = copy.deepcopy(self.original_agent_position)
        return self.map, { "Agent position" : self.agent_position}

    def step(self,action): # action = 0 dreta, 1 baix, 2 esquerra, 3 dalt
        a, b = self.agent_position
        is_agent_on_snow = self.map[a,b] == SnowmanConstants.CHARACTER_ON_SNOW_CELL        
        
        inc=[[0,1,0,-1],[1,0,-1,0]]
        next_cell=[a+inc[0][action],b+inc[1][action]] #seguent posició segons l'acció a realitzar
        next_of_next_cell=[a+2*inc[0][action],b+2*inc[1][action]] #seguent de la seguent posició segons l'acció a realitzar
    

        mov=SnowmanConstants.actions[int(self.map[next_cell[0],next_cell[1]])][int(self.map[next_of_next_cell[0],next_of_next_cell[1]])] #busca a la matri d'acions segons el que hi ha a la posició seguent i la seguent de la seguent
        reward=mov[3] # la tercera psosició es la recompensa
        mov=mov[:3] # les tres primeres posicions son que hem de col.locar a la posició del jugador, la posició seguent i la posició seguent de la seguent
        
        for i,aux in enumerate(mov):
            if aux!=None:
                if aux==SnowmanConstants.CHARACTER_LEAVE_CELL:
                    if is_agent_on_snow:
                        f=SnowmanConstants.SNOW_CELL
                    else:
                        f=SnowmanConstants.GRASS_CELL
                else:
                    f=int(aux)

                if i==0:
                    self.map[a,b]=f
                elif i==1:
                    self.map[next_cell[0],next_cell[1]]=f
                else:
                    self.map[next_of_next_cell[0],next_of_next_cell[1]]=f
        if reward==SnowmanConstants.bingo or reward<=SnowmanConstants.tonto:
            done=True
        else:
            done=False


        if action == 0:
            b = b + 1
        elif action == 1:
            a = a + 1
        elif action == 2:
            b = b - 1
        elif action == 3:
            a = a - 1
        if self.map[a,b] != SnowmanConstants.OUT_OFF_GRID_CELL or self.map[a,b] != SnowmanConstants.WALL_CELL:
            self.agent_position = (a, b)


        return self.map,reward,done, {}


    def _read_and_encode_map(self,file,n,m):
        tokens='x#,.qp1234567'
        replace_tokens=[0,0,8,9,11,10,1,2,3,4,5,6,7]
        f = open(file, "r")
        decoded_map = np.empty((n, m), dtype=np.str_)
        encoded_map = np.zeros((n,m))
        for row,linea in enumerate(f):
            linea=linea.rstrip('\n\r\t')
            for column,car in enumerate(linea):
                res = tokens.find(car)
                encoded_map[row,column]=replace_tokens[res]
                decoded_map[row, column] = car
                
        f.close()
        return encoded_map, decoded_map
    
    def show_map(self, mode):
        if mode == self.ENCODED_TEXT_MODE:
            print(self.map)
        elif mode == self.DECODED_TEXT_MODE:
            tokens = SnowmanConstants.get_cell_codes_array()
            tokens_to_replace = SnowmanConstants.get_tokens_array()
            decoded_map = copy.deepcopy(self.decoded_map)
            for i in range(self.n):
                for j in range(self.m):
                    if self.map[i,j] != SnowmanConstants.WALL_CELL or self.map[i,j] != SnowmanConstants.OUT_OFF_GRID_CELL:
                        index = tokens.index(self.map[i,j])
                        decoded_map[i,j] = tokens_to_replace[index]
            print(decoded_map)

    def split_map_layers(self):
        transform=[[0],[4],[5],[4,5],[6],[4,6],[5,6],[4,5,6],[2],[1],[1,3],[2,3]]
        splitted_map=np.zeros((self.n, self.m, 7))
        for i in range(self.n):
            for j in range(self.m):
                for k in transform[int(self.map[i][j])]:
                    splitted_map[i,j,k]=1
        return splitted_map

                    



Necessitem un replay buffer que guardi les transicions (estat, accio, seguent estat, recompensa). Definim un nou tipus Transition per fer-ho:


In [397]:
from collections import namedtuple, deque
import random

Transition = namedtuple('Transition',
                        ('state', 'action', 'next_state', 'reward'))

class ReplayMemory(object):

    def __init__(self, capacity):
        self.memory = deque([], maxlen=capacity)

    def push(self, *args):
        """Save a transition"""
        self.memory.append(Transition(*args))

    def sample(self, batch_size):
        return random.sample(self.memory, batch_size)

    def __len__(self):
        return len(self.memory)

Activem el càlcul amb GPU i definim la xara DQN neuronal convolucional.

In [398]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import matplotlib.pyplot as plt

plt.ion()
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("The model will be trained with", device)

The model will be trained with cuda


In [399]:
class DQN(nn.Module):

    def __init__(self, layers, n_actions, n, m):
        super(DQN, self).__init__()
        #conv layers params: in_channels, out_channels, kernel_size, padding=0,
        self.conv1 = nn.Conv2d(layers, 6, 3, padding=1) 
        self.conv2 = nn.Conv2d(6, 12, 3, padding=1)
        self.linear1 = nn.Linear(12*n*m, 64)
        self.linear2 = nn.Linear(64, n_actions)

    def forward(self, x):
        #print(x.shape)
        x = F.tanh(self.conv1(x))
        #print(x.shape)
        x = F.tanh(self.conv2(x))
        #print(x.shape)
        x = torch.flatten(x, 1)
        #print(x.shape)
        x = F.tanh(self.linear1(x))
        #print(x.shape)
        x = F.softmax(self.linear2(x),  dim=1)

        return x

Definim alguns hiperparametres i llavors per fer reproduible les proves:

In [400]:
np.random.seed(13)
torch.manual_seed(13)

map_rows=7
map_cols=7

BATCH_SIZE = 128 #mida del batch del replay
GAMMA = 0.99 #factor de descompte de les recompeses futures
EPS_START = 0.9 #valor inicial de la epsilon per la epsilon greedy policy
EPS_END = 0.05 #valor final de la epsilon per la epsilon greedy policy
EPS_DECAY = 1000 #controla la caiguda expoencial del valor epsilon, com més alt, mes lent disminueix
TAU = 0.005 #controla cada quan s'actualitza la target network
LR = 1e-4 #Learning rate de l'optimitzador

#Registrem l'environment al gym per poder utilitzar el mètodes de la superclase. Pot ser útil per render i algunes implementacions.
#Per exemple el baseline pot executar algorismes amb environments personalitzats sempre que implementin alguns mètodes de gym. 

gym.register(
    id='Snowman-v1.0',
    entry_point='__main__:SnowmanEnvironment',
)

snowman_gym_env = gym.make('__main__:Snowman-v1.0', map_file='./Dades/adam.txt', n=7, m=7)

In [401]:



snowman_env = SnowmanEnvironment('./Dades/adam.txt', map_rows, map_cols)
print("***************************DECODED MAP****************************")
snowman_env.show_map(SnowmanEnvironment.ENCODED_TEXT_MODE)
print("\n")
print("***************************ECODED MAP****************************")
snowman_env.show_map(SnowmanEnvironment.DECODED_TEXT_MODE)
print("\n")

n_actions =snowman_gym_env.action_space.n
print(n_actions)

state, info = snowman_gym_env.reset()





***************************DECODED MAP****************************
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  9.  9.  9.  9.  9.  0.]
 [ 0.  9.  0.  8.  0.  9.  0.]
 [ 0.  9.  1.  1.  1.  9.  0.]
 [ 0.  9.  0. 11.  0.  9.  0.]
 [ 0.  9.  9.  9.  9.  9.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


***************************ECODED MAP****************************
[['#' '#' '#' '#' '#' '#' '#']
 ['#' '.' '.' '.' '.' '.' '#']
 ['#' '.' '#' ',' '#' '.' '#']
 ['#' '.' '1' '1' '1' '.' '#']
 ['#' '.' '#' 'q' '#' '.' '#']
 ['#' '.' '.' '.' '.' '.' '#']
 ['#' '#' '#' '#' '#' '#' '#']]


4


Creem les dues xarxes neuronals i el replay memory:

In [402]:
import math

class TrainingAgent:
    def __init__(self, policy_net, target_net, replay_memory):
        self.policy_net = policy_net
        self.target_net = target_net
        self.replay_memory = replay_memory
        self.steps_done = 0

    
    def select_action_epsilon_greedy(self,state, environment):
        sample = random.random()
        eps_threshold = EPS_END + (EPS_START - EPS_END) * math.exp(-1. * self.steps_done / EPS_DECAY)
        self.steps_done = self.steps_done+1
        if sample > eps_threshold:
            with torch.no_grad():
                return self.policy_net(state).max(1).indices.view(1, 1)
        else:
            return torch.tensor([[environment.action_space.sample()]], device=device, dtype=torch.long)
        

        



In [403]:
policy_net = DQN(7, n_actions, map_rows, map_cols).to(device)
target_net = DQN(7, n_actions, map_rows, map_cols).to(device)
target_net.load_state_dict(policy_net.state_dict())

memory = ReplayMemory(10000)

training_agent = TrainingAgent(policy_net, target_net, memory)

#print(snowman_env.split_map_layers())
a = training_agent.select_action_epsilon_greedy(torch.tensor([snowman_env.split_map_layers()], device=device, dtype=torch.float32), snowman_env)
print(a)


tensor([[3]], device='cuda:0')
